keys:
  - &fokus age1cag8j93g8jjw860fwecrcl4qvvmk7k9e00puehxacy6dl55ye5eqsg7h7a
  - &nixnas age1pcsgd5f5yefxk9667j40hsr8ereky6ufxhmda5dh0fzkajpzf5as9lcw36
  - &nixadguard age13xy8pp8z4snajjvxmuhgjzutrggerqafy7t48uxuperrgsa84c2scr3v8z
  - &nixcloud age16a49l2a56x7cggxrm435s4lldxsq3ntwclc8z8426kg953xk5pjqpcytwd
  - &nixnginx age19a786mf6j8dd4p8knqz55j7hszaa8xx0u5sd738g2ws59ththu2qtnce6m
  - &nixbuild age1wnyjcxf6jjc60tdgaf4eaf3hcmpkvx25mjtc6tmhy8j9689tp9lq7nw262
  - &nixpostgres age135a39l9pweag59mdvzjs34ndmpza2utd7tew2j6s4fpffnqgf54suqltru
  - &nixzitadel age1l2v88kf7xew0ud8z06hr23r36kzxm833l338u8ku44xrn7due96q27vgqy
  - &nixheadscale age1r8yfrag9k269xzvyjp8z2p9kl97v55xaruzhl5ylql7g5z0f0cssk2yn23
  - &nixhedgedoc age1s6mwpas3nql8ve3pvrna0ecpd5gve2cem7c0yvzg4fe8r4dnc9jqm7ug7f
  - &nixgrafana age1sj998jequkhv0qqrx8futqvemy75080guz7zna0v6kz5hvtfxv6qtacary
  - &nixinflux age12pdk27hcxvk8fgc7r0rtt8l4tzjaghppgj3suyuz4vuqzlnft43sa6cjsy
  - &nixpaperless age1cckct34a8k96kwcq7yqzruhal04pgw65yrvew6pceuhrxqeyn53slfgeak
  - &nixhomeassistant age1jj90rpvwju98ssmp4n2755fa6zmcyql489k8qh6hnnwfg4fmdcyscm4k3h
creation_rules:
  - path_regex: hosts/nixnas/secrets/[^/]+\.(yaml|json|env|ini)$
    key_groups:
    - age: [*nixnas, *fokus]

  # --- LXC Service Containers (Specific Isolation) ---


  - path_regex: services/hedgedoc/.*\.enc\.yaml$
    key_groups:
    - age: [*nixhedgedoc, *fokus]

  - path_regex: services/adguard/.*\.enc\.yaml$
    key_groups:
    - age: [*nixadguard, *fokus]

  # Headscale & Headplane
  - path_regex: services/headscale/.*\.enc\.yaml$
    key_groups:
      - age: [*nixheadscale, *fokus]

  # Adguard (LXC version)
  - path_regex: services/adguardhome/.*\.enc\.yaml$
    key_groups:
      - age: [*nixadguard, *fokus]

  # Postgres & Zitadel (Shared group because Zitadel needs Postgres credentials)
  - path_regex: services/(postgres|zitadel)/.*\.enc\.yaml$
    key_groups:
      - age: [*nixpostgres, *nixzitadel, *fokus]

  # Paperless
  - path_regex: services/paperless/.*\.enc\.yaml$
    key_groups:
      - age: [*nixpaperless, *fokus]

  # Monitoring Stack
  - path_regex: services/(influxv2|grafana)/.*\.enc\.yaml$
    key_groups:
      - age: [*nixinflux, *nixgrafana, *fokus]

  # Home Automation
  - path_regex: services/home-assistant/.*\.enc\.yaml$
    key_groups:
      - age: [*nixhomeassistant, *fokus]

  # Networking & Others
  - path_regex: services/nginx/.*\.enc\.yaml$
    key_groups:
      - age: [*nixnginx, *fokus]

  - path_regex: services/netbox/.*\.enc\.yaml$
    key_groups:
      - age: [*nixheadscale, *fokus] # Adjust if netbox has its own key

  # Catch-all for any other services (Safety net for the NAS)
  - path_regex: services/.*\.enc\.yaml$
    key_groups:
      - age: [*nixnas, *fokus]