GRAFANA_ADMIN_PASSWORD: ENC[AES256_GCM,data:9aiaK8U3LFVQhOpGhsh6hx7M1oNLw5ITXm1RjYZ/wJFIn5HsGGb/sHzlEL5THUYLqct4CcGUDiyU5izf,iv:6Fl87lAXcpcNB+Je+Q9UPlRWy/ypNgHFbK8OsRSBkRs=,tag:VtHYWlTcZLEaAgq8yFL/hA==,type:str]
dsp25-ssh: ENC[AES256_GCM,data:uayqUVTq4vpDDBS18yhO4g/ORxJd5Y7fCjmcOLkV/M0PieCkzjoQH5Ei+gicyRmPGA/BFEwzLelrDPbOMwQDpX06z3ps8/j/CSkiqU5WReNLDOKz419J4TM7ATx4nYAqmVL1k6sQaW98C3g2ITsJtFDwNjKr78ZJxm52SvAwpw8GxkbDGsO4,iv:XP918ersfRlvBML35rF/QdcibKCL+xRJn14I2yMkrrg=,tag:R/kXxPzTJcRe6/1XoZ8/8w==,type:str]
sops:
    age:
        - recipient: age12pdk27hcxvk8fgc7r0rtt8l4tzjaghppgj3suyuz4vuqzlnft43sa6cjsy
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4aHpvcnZSb1hyeDgrOGZQ
            UFRVa1l4cUphWWtzUHJJdzhEYzUvaGVwS1FBCmI3QVpCc3QzVVhMTmNlUDJ3SWEv
            RzVMTHN3bWlpQ3hBQ0tHOG5pSXdiRDgKLS0tIEtrU3l1dWpxMHJDZThRVzhRQTk1
            clVkYjYycFFaKzY0Z2VxT0xCeXZqbXMKrbBHzDoUSsYmv+n18iipVLuhPE/yUB3B
            5f82INScU+xahPsU6hju712eywVfI+ySJCKRCvvRS4DG6vw/9D0j1w==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1sj998jequkhv0qqrx8futqvemy75080guz7zna0v6kz5hvtfxv6qtacary
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxRFRKS2VvYlMvWk1zS2Ns
            bGt0TlFodVdpdHo4dVpMNkxsbVduczJERG0wCmlxQlF5SVJudW13Vk0rbDF0dUZu
            OGMwbHVYZkJwUlpQTGNXa3ZnY2xiZ2MKLS0tIHJ0RW1PRXE4QTR6dnpId0ZKdXhY
            R3lFUDlKNWd5R1lZeDhWY0RneGZNTGMKuHBGP8JS8Yi1jmfB4OsFgSxl2FrTOnnR
            XQ8wqcdIHN4Mx5wp6O60v/txl4GcYE9geukZiwuCKbU3Vq9yyhmKLg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1cag8j93g8jjw860fwecrcl4qvvmk7k9e00puehxacy6dl55ye5eqsg7h7a
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAydEw0RlMvVlExbVJsQzFy
            Rk5rRXR4Z0RXTHh1STRVbXZSYnc0K25iaGs0Cm50SXg0VDA5SEZ2K0FQd3czeWIw
            UEpSeElBTFZIcUJrZUtjclZpTlQ4bW8KLS0tIGNyU04zVTNKQ0hPS0VNQTVNcThY
            cFBWZnNHSUNsNGo2cjZ4S0Z5bnByMzAKhTCW+lA1L4TimqtIRv3EqiAykcU2YaVI
            6QVnOOqpT6pKzVWz9zKSNoDixcqnZ3YOsdNyV5QuDW9h12C0UWO3Hw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1vm9pqxhup6gkekltk4j8k6kzxzpz5kugmtytzmc8vcphd70t73ssycmm4t
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXc25DV1RnQk1yaUx3OVdC
            T0pmTk1IdG1WMVNwUzl3NU1aMlhJNjdaaGpvClFWV0txQW0wZ0tNNDJsYWFCK2tt
            RnFuUE9VZTJwMU5ld1kvQmJNeDlwWTgKLS0tIEJxb3FhS3cwL2pDTFE4dlNUVm9a
            cks0RzRHTTJ6eXlPOXNxbnVydS9FbDgKQxX8NmiRxaM6XiW/1opBYP4zwan2gmrA
            THsqxcrLGANi4iwRW9iAgEK5pJsRm1b22X8sa5Y20IBuyavszsUiVQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-24T22:05:00Z"
    mac: ENC[AES256_GCM,data:Gnkhtizp7JYaknqzsCGjNr988OS24F1qlwhmuqjTP6seB/0B/GbrAdZsC7D0RXvs5Vv65e/p383KnTYhU4UyOcz/4D+K431dkwi45Xig6mwrfK58P4YdjDfBL99d3dYb8523boYUN8Bp351wwvFjxkJ8cTWtefrFmfWAgXXF0gM=,iv:R3808V3wQlNwGlKwFjihdw2dFj0/S3aWd5EYMKGAsNQ=,tag:0FB7Q7lIHtLXshZHAfiXCg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
